name: Build Plugin

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Set up Node.js (Node 20)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Trigger Generate Changelog Workflow
      - name: Trigger Generate Changelog Workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "generate-changelog"}'

      # Wait for changelog generation
      - name: Wait for Changelog Generation
        run: |
          echo "Waiting for the Generate Changelog workflow to complete..."
          sleep 30  # Replace this with a loop or more advanced logic if needed

      # Build Plugin Zip
      - name: Build Plugin Zip
        run: zip -r slm-plus.zip . -x '*.git*' '*.github*'

      # Upload Release with Changelog
      - name: Upload Release with Changelog
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          name: ${{ github.event.release.tag_name }}
          body: |
            ## Changelog
            $(cat CHANGELOG.md)  # Append the contents of the CHANGELOG.md
          artifacts: "slm-plus.zip"
          allowUpdates: true
