name: Build and Upload Release Asset

on:
  push:
    tags:
      - '*'  # Runs on any tag push
  release:
    types:
      - published  # Runs when a release is published
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Create a build directory and copy necessary files
      - name: Prepare build directory
        run: |
          mkdir build
          rsync -av --progress . build/slm-plus --exclude-from=<(echo "
            .gitignore
            .changelog.md
            security.md
            _config.yml
            composer.json
            build.xml
            package.json
            package-lock.json
            .github
            .vscode
            samples
          ")

      # Step 4: Create the ZIP file
      - name: Create ZIP archive
        run: |
          cd build
          zip -r ../slm-plus.zip slm-plus
        shell: bash

      # Step 5: Upload the ZIP as a release asset
      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: slm-plus.zip
          asset_name: slm-plus.zip
          asset_content_type: application/zip
