name: Generate Changelog

on:
  push:
    tags:
      - '*'      # Triggers for tags like 1.0, 2.1, etc.
      - 'v*'     # Also triggers for tags like v1.0, v2.1, etc.

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Git user for commit
      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Generate Changelog Content
      - name: Generate Changelog
        id: changelog
        run: |
          # Get the latest tag, ignoring any 'v' prefix if present
          latest_tag=$(git describe --tags --abbrev=0 HEAD^ | sed 's/^v//')
          
          # Generate changelog for commits since the last tag
          echo "## Changelog" > CHANGELOG.md
          echo "### Changes since $latest_tag" >> CHANGELOG.md
          git log ${latest_tag}..HEAD --pretty=format:"* %s: %b ([View Commit](https://github.com/${{ github.repository }}/commit/%H))" --no-merges >> CHANGELOG.md
          
          # Show the generated changelog
          cat CHANGELOG.md

      # Commit and Push the Changelog
      - name: Commit and push changes
        run: |
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for new release"
          git push
