name: Release Drafter

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to monitor
  pull_request:
    types: [closed]  # Trigger when a pull request is merged
  workflow_dispatch:  # Allow manual triggers

jobs:
  update_release_draft:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up the Release Drafter
      - name: Update Release Draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: .github/release-drafter.yml

      # Optionally commit and push the generated changelog if you want to update it in the repository
      - name: Commit and Push Changelog
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for new release"
          git push
